# Generated by Django 3.1 on 2024-11-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_city_id_alter_hall_id_alter_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='show',
            name='seats',
            field=models.JSONField(default={'A': {1: 'Vacant', 2: 'Vacant', 3: 'Vacant', 4: 'Vacant', 5: 'Vacant', 6: 'Vacant', 7: 'Vacant', 8: 'Vacant'}, 'B': {1: 'Vacant', 2: 'Vacant', 3: 'Vacant', 4: 'Vacant', 5: 'Vacant', 6: 'Vacant', 7: 'Vacant', 8: 'Vacant'}, 'C': {1: 'Vacant', 2: 'Vacant', 3: 'Vacant', 4: 'Vacant', 5: 'Vacant', 6: 'Vacant', 7: 'Vacant', 8: 'Vacant'}, 'D': {1: 'Vacant', 2: 'Vacant', 3: 'Vacant', 4: 'Vacant', 5: 'Vacant', 6: 'Vacant', 7: 'Vacant', 8: 'Vacant'}, 'E': {1: 'Vacant', 2: 'Vacant', 3: 'Vacant', 4: 'Vacant', 5: 'Vacant', 6: 'Vacant', 7: 'Vacant', 8: 'Vacant'}, 'F': {1: 'Vacant', 2: 'Vacant', 3: 'Vacant', 4: 'Vacant', 5: 'Vacant', 6: 'Vacant', 7: 'Vacant', 8: 'Vacant'}, 'G': {1: 'Vacant', 2: 'Vacant', 3: 'Vacant', 4: 'Vacant', 5: 'Vacant', 6: 'Vacant', 7: 'Vacant', 8: 'Vacant'}}),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
