# Generated by Django 3.1 on 2024-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20241125_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ott',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('poster', models.URLField(max_length=500)),
                ('about', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
