# Generated by Django 3.1 on 2024-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_ott'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='url',
            field=models.URLField(default='https://default-url.com'),
        ),
    ]
